name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs every day at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Last run: $(date)" > last-run.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "24f2002097@ds.study.iitm.ac.in"

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Automated daily commit - $(date)" || echo "No changes to commit"
          git push origin main

