name: Daily Commit

on:
  schedule:
    # Runs daily at 02:30 UTC (Adjust if needed)
    - cron: '30 2 * * *'

  workflow_dispatch:  # Allows manual execution if needed

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a commit - 24f2002097@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last-run.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "24f2002097@ds.study.iitm.ac.in"
          git add last-run.txt
          git commit -m "Automated daily commit - $(date)"
          git push
